development: &development
  database: book_storm_development
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 10
  username: <%= Rails.application.credentials[:development][:database][:username] %>
  password: <%= Rails.application.credentials[:development][:database][:password] %>

test:
  <<: *development
  database: book_storm_test

preparing:
  <<: *development
  database: book_storm_preparing
  username: <%= Rails.application.credentials[:preparing][:database][:username] %>
  password: <%= Rails.application.credentials[:preparing][:database][:password] %>

production:
  <<: *development
  database: book_storm_production
  username: <%= Rails.application.credentials[:production][:database][:username] %>
  password: <%= Rails.application.credentials[:production][:database][:password] %>
